[tox]
envlist = py,coverage-report,typing,lint
isolated_build = True

[docker:postgres]
image = postgres:18
environment =
    POSTGRES_PASSWORD=INSECURE-PASSWORD
    POSTGRES_USER=obsforge
    POSTGRES_DB=obsdb
# The healthcheck ensures that tox-docker won't run tests until the
# container is up and the command finishes with exit code 0 (success)
healthcheck_cmd = PGPASSWORD=$POSTGRES_PASSWORD psql \
    --user=$POSTGRES_USER --dbname=$POSTGRES_DB \
    --host=127.0.0.1 --quiet --no-align --tuples-only \
    -1 --command="SELECT 1"
healthcheck_timeout = 1
healthcheck_retries = 30
healthcheck_interval = 1
healthcheck_start_period = 1

[docker:redis]
image = redis:8
healthcheck_cmd = redis-cli ping
healthcheck_timeout = 1
healthcheck_retries = 30
healthcheck_interval = 1
healthcheck_start_period = 1

[testenv]
description = Run pytest against {envname}.
runner = uv-venv-lock-runner
commands =
    pytest --cov=obsforge --cov-branch --cov-report= {posargs}
setenv =
    OBSFORGE_ARQ_MODE = production
    OBSFORGE_ARQ_QUEUE_URL = redis://localhost/0
    OBSFORGE_DATABASE_URL = postgresql://obsforge@localhost/obsdb
    OBSFORGE_DATABASE_PASSWORD = INSECURE-PASSWORD

[testenv:alembic]
description = Run Alembic against a test database.
commands =
    alembic {posargs}
docker =
    postgres
setenv =
    OBSFORGE_ALEMBIC_CONFIG_PATH = {toxinidir}/alembic.ini
    OBSFORGE_DATABASE_URL = postgresql://obsforge@localhost/obsdb
    OBSFORGE_DATABASE_PASSWORD = INSECURE-PASSWORD

[testenv:coverage-report]
description = Compile coverage from each test run.
commands = coverage report
package = skip
depends =
    py

[testenv:py]
description = Run pytest with PostgreSQL and Redis.
docker =
    postgres
    redis

[testenv:py-mock-arq]
description = Run pytest with PostgreSQL and the mocked arq queue.
commands =
    pytest --cov=obsforge --cov-branch --cov-report= tests/handlers/arq_test.py {posargs}
docker =
    postgres
setenv =
    OBSFORGE_ARQ_MODE = test
    OBSFORGE_DATABASE_URL = postgresql://obsforge@localhost/obsdb
    OBSFORGE_DATABASE_PASSWORD = INSECURE-PASSWORD

[testenv:lint]
description = Lint codebase by running pre-commit.
commands = pre-commit run --all-files
package = skip
uv_sync_flags = --only-group, lint

[testenv:run]
description = Run the development server with auto-reload for code changes.
usedevelop = true
commands = uvicorn obsforge.main:app --reload

[testenv:typing]
description = Run mypy.
commands =
    mypy src/obsforge tests
package = skip
dependency_groups =
    dev
    typing

[testenv:obsforge]
description = Run command-line tool against a test database.
commands =
    obsforge {posargs}
docker =
    postgres
setenv =
    OBSFORGE_ALEMBIC_CONFIG_PATH = {toxinidir}/alembic.ini
    OBSFORGE_DATABASE_URL = postgresql://obsforge@localhost/obsdb
    OBSFORGE_DATABASE_PASSWORD = INSECURE-PASSWORD
